//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeJewels.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public string AuthorMail { get; set; }
        public int CodeJewelId { get; set; }
    
        public virtual CodeJewel CodeJewel { get; set; }
    }
}
